<?php

namespace Database\Seeders;
use App\Models\Pokemon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PokemonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate the table (reset the IDs and delete all data)
        Pokemon::truncate();

        // Insert multiple Pokémon as an array of arrays
        Pokemon::insert([
            [
                'name' => 'Bulbasaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => 6.90,
                'height' => 0.70,
                'hp' => 45,
                'attack' => 49,
                'defense' => 49,
                'is_legendary' => 0,
                'photo' => 'public/bulbasaur.png',
            ],
            [
                'name' => 'Ivysaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => 13.00,
                'height' => 1.00,
                'hp' => 60,
                'attack' => 62,
                'defense' => 63,
                'is_legendary' => 0,
                'photo' => 'public/ivysaur.png',
            ],
            [
                'name' => 'Venusaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => 100.00,
                'height' => 2.00,
                'hp' => 80,
                'attack' => 100,
                'defense' => 123,
                'is_legendary' => 0,
                'photo' => 'public/venusaur.png',
            ],
            [
                'name' => 'Charmander',
                'species' => 'Lizard Pokemon',
                'primary_type' => 'Fire',
                'weight' => 8.50,
                'height' => 0.60,
                'hp' => 39,
                'attack' => 52,
                'defense' => 43,
                'is_legendary' => 0,
                'photo' => 'public/charmander.png',
            ],
            [
                'name' => 'Charmeleon',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => 19.00,
                'height' => 1.10,
                'hp' => 58,
                'attack' => 64,
                'defense' => 58,
                'is_legendary' => 0,
                'photo' => 'public/charmeleon.png',
            ],
            [
                'name' => 'Charizard',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => 90.50,
                'height' => 1.70,
                'hp' => 78,
                'attack' => 104,
                'defense' => 78,
                'is_legendary' => 0,
                'photo' => 'public/charizard.png',
            ],
            [
                'name' => 'Squirtle',
                'species' => 'Tiny Turtle Pokemon',
                'primary_type' => 'Water',
                'weight' => 9.00,
                'height' => 0.50,
                'hp' => 44,
                'attack' => 48,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/squirtle.png',
            ],
            [
                'name' => 'Wartortle',
                'species' => 'Turtle Pokemon',
                'primary_type' => 'Water',
                'weight' => 22.50,
                'height' => 1.00,
                'hp' => 59,
                'attack' => 63,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/wartortle.png',
            ],
            [
                'name' => 'Blastoise',
                'species' => 'Shellfish Pokemon',
                'primary_type' => 'Water',
                'weight' => 85.50,
                'height' => 1.60,
                'hp' => 79,
                'attack' => 103,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'public/blastoise.png',
            ],
            [
                'name' => 'Caterpie',
                'species' => 'Worm Pokemon',
                'primary_type' => 'Bug',
                'weight' => 2.90,
                'height' => 0.30,
                'hp' => 45,
                'attack' => 30,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/caterpie.png',
            ],
            [
                'name' => 'Metapod',
                'species' => 'Cocoon Pokemon',
                'primary_type' => 'Bug',
                'weight' => 9.90,
                'height' => 0.70,
                'hp' => 50,
                'attack' => 20,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/metapod.png',
            ],
            [
                'name' => 'Butterfree',
                'species' => 'Butterfly Pokemon',
                'primary_type' => 'Bug',
                'weight' => 32.00,
                'height' => 1.10,
                'hp' => 60,
                'attack' => 45,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/butterfree.png',
            ],
            [
                'name' => 'Weedle',
                'species' => 'Hairy Pokemon',
                'primary_type' => 'Bug',
                'weight' => 3.20,
                'height' => 0.30,
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/weedle.png',
            ],
            [
                'name' => 'Kakuna',
                'species' => 'Cocoon Pokemon',
                'primary_type' => 'Bug',
                'weight' => 10.00,
                'height' => 0.60,
                'hp' => 45,
                'attack' => 25,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/kakuna.png',
            ],
            [
                'name' => 'Beedrill',
                'species' => 'Poison Bee Pokemon',
                'primary_type' => 'Bug',
                'weight' => 29.50,
                'height' => 1.00,
                'hp' => 65,
                'attack' => 150,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/beedrill.png',
            ],
            [
                'name' => 'Pidgey',
                'species' => 'Tiny Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => 1.80,
                'height' => 0.30,
                'hp' => 40,
                'attack' => 45,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/pidgey.png',
            ],
            [
                'name' => 'Pidgeotto',
                'species' => 'Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => 30.00,
                'height' => 1.10,
                'hp' => 63,
                'attack' => 60,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/pidgeotto.png',
            ],
            [
                'name' => 'Pidgeot',
                'species' => 'Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => 39.50,
                'height' => 1.50,
                'hp' => 83,
                'attack' => 80,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/pidgeot.png',
            ],
            [
                'name' => 'Rattata',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Normal',
                'weight' => 3.75,
                'height' => 0.30,
                'hp' => 30,
                'attack' => 56,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/rattata.png',
            ],
            [
                'name' => 'Raticate',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Normal',
                'weight' => 18.50,
                'height' => 0.70,
                'hp' => 75,
                'attack' => 71,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/raticate.png',
            ],
            [
                'name' => 'Spearow',
                'species' => 'Tiny Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => 2.00,
                'height' => 0.30,
                'hp' => 40,
                'attack' => 60,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/spearow.png',
            ],
            [
                'name' => 'Fearow',
                'species' => 'Beak Pokemon',
                'primary_type' => 'Normal',
                'weight' => 38.00,
                'height' => 1.20,
                'hp' => 65,
                'attack' => 90,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/fearow.png',
            ],
            [
                'name' => 'Ekans',
                'species' => 'Snake Pokemon',
                'primary_type' => 'Poison',
                'weight' => 6.90,
                'height' => 2.00,
                'hp' => 35,
                'attack' => 60,
                'defense' => 44,
                'is_legendary' => 0,
                'photo' => 'public/ekans.png',
            ],
            [
                'name' => 'Arbok',
                'species' => 'Cobra Pokemon',
                'primary_type' => 'Poison',
                'weight' => 65.00,
                'height' => 3.50,
                'hp' => 60,
                'attack' => 95,
                'defense' => 69,
                'is_legendary' => 0,
                'photo' => 'public/arbok.png',
            ],
            [
                'name' => 'Pikachu',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Electric',
                'weight' => 6.00,
                'height' => 0.40,
                'hp' => 35,
                'attack' => 55,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/pikachu.png',
            ],
            [
                'name' => 'Nidoran ♂',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => 7.00,
                'height' => 0.40,
                'hp' => 55,
                'attack' => 47,
                'defense' => 52,
                'is_legendary' => 0,
                'photo' => 'public/nidoran-m.png',
            ],
            [
                'name' => 'Nidorina',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => 20.00,
                'height' => 0.80,
                'hp' => 70,
                'attack' => 62,
                'defense' => 67,
                'is_legendary' => 0,
                'photo' => 'public/nidorina.png',
            ],
            [
                'name' => 'Nidoqueen',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Poison',
                'weight' => 60.00,
                'height' => 1.30,
                'hp' => 90,
                'attack' => 92,
                'defense' => 87,
                'is_legendary' => 0,
                'photo' => 'public/nidoqueen.png',
            ],
            [
                'name' => 'Nidoran ♀',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => 9.00,
                'height' => 0.50,
                'hp' => 46,
                'attack' => 57,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/nidoran-f.png',
            ],
            [
                'name' => 'Nidorino',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => 19.50,
                'height' => 0.90,
                'hp' => 61,
                'attack' => 72,
                'defense' => 57,
                'is_legendary' => 0,
                'photo' => 'public/nidorino.png',
            ],
            [
                'name' => 'Nidoking',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Poison',
                'weight' => 62.00,
                'height' => 1.40,
                'hp' => 81,
                'attack' => 102,
                'defense' => 77,
                'is_legendary' => 0,
                'photo' => 'public/nidoking.png',
            ],
            [
                'name' => 'Clefairy',
                'species' => 'Fairy Pokemon',
                'primary_type' => 'Fairy',
                'weight' => 7.50,
                'height' => 0.60,
                'hp' => 70,
                'attack' => 45,
                'defense' => 48,
                'is_legendary' => 0,
                'photo' => 'public/clefairy.png',
            ],
            [
                'name' => 'Clefable',
                'species' => 'Fairy Pokemon',
                'primary_type' => 'Fairy',
                'weight' => 40.00,
                'height' => 1.30,
                'hp' => 95,
                'attack' => 70,
                'defense' => 73,
                'is_legendary' => 0,
                'photo' => 'public/clefable.png',
            ],
            [
                'name' => 'Jigglypuff',
                'species' => 'Balloon Pokemon',
                'primary_type' => 'Normal',
                'weight' => 5.50,
                'height' => 0.50,
                'hp' => 115,
                'attack' => 45,
                'defense' => 20,
                'is_legendary' => 0,
                'photo' => 'public/jigglypuff.png',
            ],
            [
                'name' => 'Wigglytuff',
                'species' => 'Balloon Pokemon',
                'primary_type' => 'Normal',
                'weight' => 12.00,
                'height' => 1.00,
                'hp' => 140,
                'attack' => 70,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/wigglytuff.png',
            ],
            [
                'name' => 'Zubat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => 7.50,
                'height' => 0.80,
                'hp' => 40,
                'attack' => 45,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/zubat.png',
            ],
            [
                'name' => 'Zubat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => '7.50',
                'height' => '0.80',
                'hp' => 40,
                'attack' => 45,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/zubat.png',
            ],
            [
                'name' => 'Golbat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => '55.00',
                'height' => '1.60',
                'hp' => 75,
                'attack' => 80,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/golbat.png',
            ],
            [
                'name' => 'Oddish',
                'species' => 'Weed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '5.40',
                'height' => '0.50',
                'hp' => 45,
                'attack' => 50,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/oddish.png',
            ],
            [
                'name' => 'Gloom',
                'species' => 'Weed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '8.60',
                'height' => '0.80',
                'hp' => 60,
                'attack' => 65,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/gloom.png',
            ],
            [
                'name' => 'Vileplume',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '18.60',
                'height' => '1.20',
                'hp' => 75,
                'attack' => 80,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'public/vileplume.png',
            ],
            [
                'name' => 'Paras',
                'species' => 'Mushroom Pokemon',
                'primary_type' => 'Bug',
                'weight' => '5.40',
                'height' => '0.30',
                'hp' => 35,
                'attack' => 70,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/paras.png',
            ],
            [
                'name' => 'Parasect',
                'species' => 'Mushroom Pokemon',
                'primary_type' => 'Bug',
                'weight' => '29.50',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 95,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/parasect.png',
            ],
            [
                'name' => 'Venonat',
                'species' => 'Insect Pokemon',
                'primary_type' => 'Bug',
                'weight' => '30.00',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 55,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/venonat.png',
            ],
            [
                'name' => 'Venomoth',
                'species' => 'Poison Moth Pokemon',
                'primary_type' => 'Bug',
                'weight' => '12.50',
                'height' => '1.50',
                'hp' => 70,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/venomoth.png',
            ],
            [
                'name' => 'Psyduck',
                'species' => 'Duck Pokemon',
                'primary_type' => 'Water',
                'weight' => '19.60',
                'height' => '0.80',
                'hp' => 50,
                'attack' => 52,
                'defense' => 48,
                'is_legendary' => 0,
                'photo' => 'public/psyduck.png',
            ],
            [
                'name' => 'Golduck',
                'species' => 'Duck Pokemon',
                'primary_type' => 'Water',
                'weight' => '76.60',
                'height' => '1.70',
                'hp' => 80,
                'attack' => 82,
                'defense' => 78,
                'is_legendary' => 0,
                'photo' => 'public/golduck.png',
            ],
            [
                'name' => 'Mankey',
                'species' => 'Pig Monkey Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '28.00',
                'height' => '0.50',
                'hp' => 40,
                'attack' => 80,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/mankey.png',
            ],
            [
                'name' => 'Primeape',
                'species' => 'Pig Monkey Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '32.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 105,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/primeape.png',
            ],
            [
                'name' => 'Growlithe',
                'species' => 'Puppy Pokemon',
                'primary_type' => 'Fire',
                'weight' => '19.00',
                'height' => '0.70',
                'hp' => 55,
                'attack' => 70,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/growlithe.png',
            ],
            [
                'name' => 'Arcanine',
                'species' => 'Legendary Pokemon',
                'primary_type' => 'Fire',
                'weight' => '155.00',
                'height' => '1.90',
                'hp' => 90,
                'attack' => 110,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/arcanine.png',
            ],
            [
                'name' => 'Poliwag',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '12.40',
                'height' => '0.60',
                'hp' => 40,
                'attack' => 50,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/poliwag.png',
            ],
            [
                'name' => 'Poliwhirl',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '20.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 65,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/poliwhirl.png',
            ],
            [
                'name' => 'Poliwrath',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '54.00',
                'height' => '1.30',
                'hp' => 90,
                'attack' => 95,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/poliwrath.png',
            ],
            [
                'name' => 'Abra',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '19.50',
                'height' => '0.90',
                'hp' => 25,
                'attack' => 20,
                'defense' => 15,
                'is_legendary' => 0,
                'photo' => 'public/abra.png',
            ],
            [
                'name' => 'Kadabra',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '56.50',
                'height' => '1.30',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/kadabra.png',
            ],
            [
                'name' => 'Alakazam',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '48.00',
                'height' => '1.50',
                'hp' => 55,
                'attack' => 50,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/alakazam.png',
            ],
            [
                'name' => 'Machop',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '19.50',
                'height' => '0.80',
                'hp' => 70,
                'attack' => 80,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/machop.png',
            ],
            [
                'name' => 'Machoke',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '70.50',
                'height' => '1.50',
                'hp' => 80,
                'attack' => 100,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/machoke.png',
            ],
            [
                'name' => 'Machamp',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '130.00',
                'height' => '1.60',
                'hp' => 90,
                'attack' => 130,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/machamp.png',
            ],
            [
                'name' => 'Bellsprout',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '4.00',
                'height' => '0.70',
                'hp' => 50,
                'attack' => 75,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/bellsprout.png',
            ],
            [
                'name' => 'Weepinbell',
                'species' => 'Flycatcher Pokemon',
                'primary_type' => 'Grass',
                'weight' => '6.40',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 90,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/weepinbell.png',
            ],
            [
                'name' => 'Victreebel',
                'species' => 'Flycatcher Pokemon',
                'primary_type' => 'Grass',
                'weight' => '15.50',
                'height' => '1.70',
                'hp' => 80,
                'attack' => 105,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/victreebel.png',
            ],
            [
                'name' => 'Tentacool',
                'species' => 'Jellyfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '45.50',
                'height' => '0.90',
                'hp' => 40,
                'attack' => 40,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/tentacool.png',
            ],
            [
                'name' => 'Tentacruel',
                'species' => 'Jellyfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '55.00',
                'height' => '1.60',
                'hp' => 80,
                'attack' => 70,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/tentacruel.png',
            ],
            [
                'name' => 'Geodude',
                'species' => 'Rock Pokemon',
                'primary_type' => 'Rock',
                'weight' => '20.00',
                'height' => '0.40',
                'hp' => 40,
                'attack' => 80,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/geodude.png',
            ],
            [
                'name' => 'Graveler',
                'species' => 'Rock Pokemon',
                'primary_type' => 'Rock',
                'weight' => '105.00',
                'height' => '1.00',
                'hp' => 55,
                'attack' => 95,
                'defense' => 115,
                'is_legendary' => 0,
                'photo' => 'public/graveler.png',
            ],
            [
                'name' => 'Golem',
                'species' => 'Rock Pokemon',
                'primary_type' => 'Rock',
                'weight' => '300.00',
                'height' => '1.40',
                'hp' => 80,
                'attack' => 110,
                'defense' => 130,
                'is_legendary' => 0,
                'photo' => 'public/golem.png',
            ],
            [
                'name' => 'Ponyta',
                'species' => 'Fire Horse Pokemon',
                'primary_type' => 'Fire',
                'weight' => '30.00',
                'height' => '1.00',
                'hp' => 50,
                'attack' => 85,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/ponyta.png',
            ],
            [
                'name' => 'Rapidash',
                'species' => 'Fire Horse Pokemon',
                'primary_type' => 'Fire',
                'weight' => '95.00',
                'height' => '1.70',
                'hp' => 65,
                'attack' => 100,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/rapidash.png',
            ],
            [
                'name' => 'Slowpoke',
                'species' => 'Dopey Pokemon',
                'primary_type' => 'Water',
                'weight' => '36.00',
                'height' => '1.20',
                'hp' => 90,
                'attack' => 65,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/slowpoke.png',
            ],
            [
                'name' => 'Slowbro',
                'species' => 'Hermit Crab Pokemon',
                'primary_type' => 'Water',
                'weight' => '78.50',
                'height' => '1.60',
                'hp' => 95,
                'attack' => 75,
                'defense' => 110,
                'is_legendary' => 0,
                'photo' => 'public/slowbro.png',
            ],
            [
                'name' => 'Magnemite',
                'species' => 'Magnet Pokemon',
                'primary_type' => 'Electric',
                'weight' => '6.00',
                'height' => '0.30',
                'hp' => 25,
                'attack' => 35,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/magnemite.png',
            ],
            [
                'name' => 'Magneton',
                'species' => 'Magnet Pokemon',
                'primary_type' => 'Electric',
                'weight' => '60.00',
                'height' => '1.00',
                'hp' => 50,
                'attack' => 60,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/magneton.png',
            ],
            [
                'name' => 'Farfetch\'d',
                'species' => 'Wild Duck Pokemon',
                'primary_type' => 'Normal',
                'weight' => '15.00',
                'height' => '0.80',
                'hp' => 52,
                'attack' => 65,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/farfetchd.png',
            ],
            [
                'name' => 'Doduo',
                'species' => 'Twin Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '39.20',
                'height' => '1.40',
                'hp' => 35,
                'attack' => 85,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/doduo.png',
            ],
            [
                'name' => 'Dodrio',
                'species' => 'Twin Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '85.20',
                'height' => '1.80',
                'hp' => 60,
                'attack' => 110,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/dodrio.png',
            ],
            [
                'name' => 'Seel',
                'species' => 'Sea Lion Pokemon',
                'primary_type' => 'Water',
                'weight' => '90.00',
                'height' => '1.10',
                'hp' => 65,
                'attack' => 40,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/seel.png',
            ],
            [
                'name' => 'Dewgong',
                'species' => 'Sea Lion Pokemon',
                'primary_type' => 'Water',
                'weight' => '120.00',
                'height' => '1.70',
                'hp' => 90,
                'attack' => 70,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/dewgong.png',
            ],
            [
                'name' => 'Grimer',
                'species' => 'Sludge Pokemon',
                'primary_type' => 'Poison',
                'weight' => '30.00',
                'height' => '0.90',
                'hp' => 80,
                'attack' => 80,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/grimer.png',
            ],
            [
                'name' => 'Muk',
                'species' => 'Sludge Pokemon',
                'primary_type' => 'Poison',
                'weight' => '30.00',
                'height' => '1.00',
                'hp' => 105,
                'attack' => 105,
                'defense' => 75,
                'is_legendary' => 0,
                'photo' => 'public/muk.png',
            ],
            [
                'name' => 'Shellder',
                'species' => 'Bivalve Pokemon',
                'primary_type' => 'Water',
                'weight' => '4.00',
                'height' => '0.30',
                'hp' => 30,
                'attack' => 25,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/shellder.png',
            ],
            [
                'name' => 'Cloyster',
                'species' => 'Bivalve Pokemon',
                'primary_type' => 'Water',
                'weight' => '132.50',
                'height' => '1.50',
                'hp' => 50,
                'attack' => 95,
                'defense' => 180,
                'is_legendary' => 0,
                'photo' => 'public/cloyster.png',
            ],
            [
                'name' => 'Gastly',
                'species' => 'Gas Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '0.10',
                'height' => '1.30',
                'hp' => 30,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/gastly.png',
            ],
            [
                'name' => 'Haunter',
                'species' => 'Gas Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '0.1',
                'height' => '1.60',
                'hp' => 45,
                'attack' => 50,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/haunter.png',
            ],
            [
                'name' => 'Gengar',
                'species' => 'Shadow Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '40.50',
                'height' => '1.50',
                'hp' => 60,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/gengar.png',
            ],
            [
                'name' => 'Onix',
                'species' => 'Rock Snake Pokemon',
                'primary_type' => 'Rock',
                'weight' => '210.00',
                'height' => '8.80',
                'hp' => 35,
                'attack' => 45,
                'defense' => 160,
                'is_legendary' => 0,
                'photo' => 'public/onix.png',
            ],
            [
                'name' => 'Drowzee',
                'species' => 'Hypnosis Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '32.40',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 48,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/drowzee.png',
            ],
            [
                'name' => 'Hypno',
                'species' => 'Hypnosis Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '75.60',
                'height' => '1.60',
                'hp' => 85,
                'attack' => 73,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/hypno.png',
            ],
            [
                'name' => 'Krabby',
                'species' => 'River Crab Pokemon',
                'primary_type' => 'Water',
                'weight' => '6.50',
                'height' => '0.40',
                'hp' => 30,
                'attack' => 105,
                'defense' => 90,
                'is_legendary' => 0,
                'photo' => 'public/krabby.png',
            ],
            [
                'name' => 'Kingler',
                'species' => 'River Crab Pokemon',
                'primary_type' => 'Water',
                'weight' => '60.00',
                'height' => '1.10',
                'hp' => 55,
                'attack' => 130,
                'defense' => 115,
                'is_legendary' => 0,
                'photo' => 'public/kingler.png',
            ],
            [
                'name' => 'Voltorb',
                'species' => 'Ball Pokemon',
                'primary_type' => 'Electric',
                'weight' => '10.00',
                'height' => '0.50',
                'hp' => 40,
                'attack' => 30,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/voltorb.png',
            ],
            [
                'name' => 'Electrode',
                'species' => 'Ball Pokemon',
                'primary_type' => 'Electric',
                'weight' => '66.00',
                'height' => '1.20',
                'hp' => 60,
                'attack' => 50,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/electrode.png',
            ],
            [
                'name' => 'Exeggcute',
                'species' => 'Egg Pokemon',
                'primary_type' => 'Grass',
                'weight' => '2.50',
                'height' => '0.40',
                'hp' => 60,
                'attack' => 40,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/exeggcute.png',
            ],
            [
                'name' => 'Exeggutor',
                'species' => 'Coconut Pokemon',
                'primary_type' => 'Grass',
                'weight' => '120.00',
                'height' => '2.00',
                'hp' => 95,
                'attack' => 95,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'public/exeggutor.png',
            ],
            [
                'name' => 'Cubone',
                'species' => 'Lonely Pokemon',
                'primary_type' => 'Ground',
                'weight' => '6.50',
                'height' => '0.40',
                'hp' => 50,
                'attack' => 50,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/cubone.png',
            ],
            [
                'name' => 'Marowak',
                'species' => 'Bone Keeper Pokemon',
                'primary_type' => 'Ground',
                'weight' => '45.00',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 80,
                'defense' => 110,
                'is_legendary' => 0,
                'photo' => 'public/marowak.png',
            ],
            [
                'name' => 'Hitmonlee',
                'species' => 'Kicking Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '49.80',
                'height' => '1.50',
                'hp' => 50,
                'attack' => 120,
                'defense' => 53,
                'is_legendary' => 0,
                'photo' => 'public/hitmonlee.png',
            ],
            [
                'name' => 'Hitmonchan',
                'species' => 'Punching Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '50.20',
                'height' => '1.40',
                'hp' => 50,
                'attack' => 105,
                'defense' => 79,
                'is_legendary' => 0,
                'photo' => 'public/hitmonchan.png',
            ],
            [
                'name' => 'Lickitung',
                'species' => 'Licking Pokemon',
                'primary_type' => 'Normal',
                'weight' => '65.50',
                'height' => '1.20',
                'hp' => 90,
                'attack' => 55,
                'defense' => 75,
                'is_legendary' => 0,
                'photo' => 'public/lickitung.png',
            ],
            [
                'name' => 'Koffing',
                'species' => 'Poison Gas Pokemon',
                'primary_type' => 'Poison',
                'weight' => '10.00',
                'height' => '0.60',
                'hp' => 40,
                'attack' => 65,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/koffing.png',
            ],
            [
                'name' => 'Weezing',
                'species' => 'Poison Gas Pokemon',
                'primary_type' => 'Poison',
                'weight' => '9.50',
                'height' => '1.20',
                'hp' => 65,
                'attack' => 90,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'public/weezing.png',
            ],
            [
                'name' => 'Rhyhorn',
                'species' => 'Spikes Pokemon',
                'primary_type' => 'Ground',
                'weight' => '115.00',
                'height' => '1.00',
                'hp' => 80,
                'attack' => 85,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/rhyhorn.png',
            ],
            [
                'name' => 'Rhydon',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Ground',
                'weight' => '120.00',
                'height' => '1.90',
                'hp' => 105,
                'attack' => 130,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'public/rhydon.png',
            ],
            [
                'name' => 'Chansey',
                'species' => 'Egg Pokemon',
                'primary_type' => 'Normal',
                'weight' => '76.00',
                'height' => '1.10',
                'hp' => 250,
                'attack' => 5,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/chansey.png',
            ],
            [
                'name' => 'Tangela',
                'species' => 'Vine Pokemon',
                'primary_type' => 'Grass',
                'weight' => '35.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 55,
                'defense' => 115,
                'is_legendary' => 0,
                'photo' => 'public/tangela.png',
            ],
            [
                'name' => 'Kangaskhan',
                'species' => 'Parent Pokemon',
                'primary_type' => 'Normal',
                'weight' => '80.00',
                'height' => '2.20',
                'hp' => 105,
                'attack' => 95,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/kangaskhan.png',
            ],
            [
                'name' => 'Horsea',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Water',
                'weight' => '8.00',
                'height' => '0.40',
                'hp' => 30,
                'attack' => 40,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/horse.png',
            ],
            [
                'name' => 'Seadra',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Water',
                'weight' => '25.00',
                'height' => '1.20',
                'hp' => 55,
                'attack' => 65,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/seadra.png',
            ],
            [
                'name' => 'Goldeen',
                'species' => 'Goldfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '15.00',
                'height' => '0.60',
                'hp' => 45,
                'attack' => 67,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/goldeen.png',
            ],
            [
                'name' => 'Seaking',
                'species' => 'Goldfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '39.00',
                'height' => '1.30',
                'hp' => 65,
                'attack' => 92,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/seaking.png',
            ],
            [
                'name' => 'Staryu',
                'species' => 'Star Shape Pokemon',
                'primary_type' => 'Water',
                'weight' => '34.50',
                'height' => '0.80',
                'hp' => 30,
                'attack' => 45,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/staryu.png',
            ],
            [
                'name' => 'Starmie',
                'species' => 'Starlight Pokemon',
                'primary_type' => 'Water',
                'weight' => '80.00',
                'height' => '1.10',
                'hp' => 60,
                'attack' => 75,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'public/starmie.png',
            ],
            [
                'name' => 'Mr. Mime',
                'species' => 'Barrier Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '54.50',
                'height' => '1.30',
                'hp' => 40,
                'attack' => 45,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/mr_mime.png',
            ],
            [
                'name' => 'Scyther',
                'species' => 'Mantis Pokemon',
                'primary_type' => 'Bug',
                'weight' => '56.00',
                'height' => '1.50',
                'hp' => 70,
                'attack' => 110,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/scyther.png',
            ],
            [
                'name' => 'Jynx',
                'species' => 'Human Shape Pokemon',
                'primary_type' => 'Ice',
                'weight' => '40.60',
                'height' => '1.40',
                'hp' => 65,
                'attack' => 50,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/jynx.png',
            ],
            [
                'name' => 'Electabuzz',
                'species' => 'Electric Pokemon',
                'primary_type' => 'Electric',
                'weight' => '30.00',
                'height' => '1.10',
                'hp' => 65,
                'attack' => 95,
                'defense' => 57,
                'is_legendary' => 0,
                'photo' => 'public/electabuzz.png',
            ],
            [
                'name' => 'Magmar',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '44.50',
                'height' => '1.30',
                'hp' => 65,
                'attack' => 95,
                'defense' => 57,
                'is_legendary' => 0,
                'photo' => 'public/magmar.png',
            ],
            [
                'name' => 'Pinsir',
                'species' => 'Stag Beetle Pokemon',
                'primary_type' => 'Bug',
                'weight' => '55.00',
                'height' => '1.50',
                'hp' => 65,
                'attack' => 125,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/pinsir.png',
            ],
            [
                'name' => 'Tauros',
                'species' => 'Bull Pokemon',
                'primary_type' => 'Normal',
                'weight' => '88.40',
                'height' => '1.40',
                'hp' => 75,
                'attack' => 100,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/tauros.png',
            ],
            [
                'name' => 'Magikarp',
                'species' => 'Fish Pokemon',
                'primary_type' => 'Water',
                'weight' => '10.00',
                'height' => '0.90',
                'hp' => 20,
                'attack' => 10,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/magikarp.png',
            ],
            [
                'name' => 'Gyarados',
                'species' => 'Atrocious Pokemon',
                'primary_type' => 'Water',
                'weight' => '235.00',
                'height' => '6.50',
                'hp' => 95,
                'attack' => 125,
                'defense' => 79,
                'is_legendary' => 0,
                'photo' => 'public/gyarados.png',
            ],
            [
                'name' => 'Lapras',
                'species' => 'Transport Pokemon',
                'primary_type' => 'Water',
                'weight' => '220.00',
                'height' => '2.50',
                'hp' => 130,
                'attack' => 85,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/lapras.png',
            ],
            [
                'name' => 'Ditto',
                'species' => 'Transform Pokemon',
                'primary_type' => 'Normal',
                'weight' => '4.00',
                'height' => '0.30',
                'hp' => 48,
                'attack' => 48,
                'defense' => 48,
                'is_legendary' => 0,
                'photo' => 'public/ditto.png',
            ],
            [
                'name' => 'Eevee',
                'species' => 'Evolution Pokemon',
                'primary_type' => 'Normal',
                'weight' => '6.50',
                'height' => '0.30',
                'hp' => 55,
                'attack' => 40,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/eevee.png',
            ],
            [
                'name' => 'Vaporeon',
                'species' => 'Bubble Jet Pokemon',
                'primary_type' => 'Water',
                'weight' => '29.00',
                'height' => '1.00',
                'hp' => 130,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/vaporeon.png',
            ],
            [
                'name' => 'Jolteon',
                'species' => 'Lightning Pokemon',
                'primary_type' => 'Electric',
                'weight' => '24.50',
                'height' => '0.80',
                'hp' => 65,
                'attack' => 110,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/jolteon.png',
            ],
            [
                'name' => 'Flareon',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '25.00',
                'height' => '0.90',
                'hp' => 65,
                'attack' => 130,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'public/flareon.png',
            ],
            [
                'name' => 'Porygon',
                'species' => 'Virtual Pokemon',
                'primary_type' => 'Normal',
                'weight' => '36.50',
                'height' => '0.80',
                'hp' => 65,
                'attack' => 60,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/porygon.png',
            ],
            [
                'name' => 'Omanyte',
                'species' => 'Dome Pokemon',
                'primary_type' => 'Rock',
                'weight' => '7.50',
                'height' => '0.40',
                'hp' => 35,
                'attack' => 40,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/omanyte.png',
            ],
            [
                'name' => 'Omastar',
                'species' => 'Shellfish Pokemon',
                'primary_type' => 'Rock',
                'weight' => '35.00',
                'height' => '1.00',
                'hp' => 70,
                'attack' => 60,
                'defense' => 125,
                'is_legendary' => 0,
                'photo' => 'public/omastar.png',
            ],
            [
                'name' => 'Kabuto',
                'species' => 'Shellfish Pokemon',
                'primary_type' => 'Rock',
                'weight' => '11.50',
                'height' => '0.50',
                'hp' => 30,
                'attack' => 40,
                'defense' => 90,
                'is_legendary' => 0,
                'photo' => 'public/kabuto.png',
            ],
            [
                'name' => 'Kabutops',
                'species' => 'Shellfish Pokemon',
                'primary_type' => 'Rock',
                'weight' => '40.50',
                'height' => '1.30',
                'hp' => 60,
                'attack' => 115,
                'defense' => 105,
                'is_legendary' => 0,
                'photo' => 'public/kabutops.png',
            ],
            [
                'name' => 'Aerodactyl',
                'species' => 'Fossil Pokemon',
                'primary_type' => 'Rock',
                'weight' => '59.00',
                'height' => '1.80',
                'hp' => 80,
                'attack' => 105,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/aerodactyl.png',
            ],
            [
                'name' => 'Snorlax',
                'species' => 'Sleeping Pokemon',
                'primary_type' => 'Normal',
                'weight' => '460.00',
                'height' => '2.10',
                'hp' => 160,
                'attack' => 110,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/snorlax.png',
            ],
            [
                'name' => 'Articuno',
                'species' => 'Ice Bird Pokemon',
                'primary_type' => 'Ice',
                'weight' => '55.40',
                'height' => '1.70',
                'hp' => 90,
                'attack' => 85,
                'defense' => 100,
                'is_legendary' => 1,
                'photo' => 'public/articuno.png',
            ],
            [
                'name' => 'Zapdos',
                'species' => 'Electric Bird Pokemon',
                'primary_type' => 'Electric',
                'weight' => '52.60',
                'height' => '1.60',
                'hp' => 90,
                'attack' => 90,
                'defense' => 85,
                'is_legendary' => 1,
                'photo' => 'public/zapdos.png',
            ],
            [
                'name' => 'Moltres',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '60.00',
                'height' => '2.00',
                'hp' => 90,
                'attack' => 100,
                'defense' => 90,
                'is_legendary' => 1,
                'photo' => 'public/moltres.png',
            ],
            [
                'name' => 'Dratini',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Dragon',
                'weight' => '3.30',
                'height' => '1.30',
                'hp' => 41,
                'attack' => 64,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/dratini.png',
            ],
            [
                'name' => 'Dragonair',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Dragon',
                'weight' => '16.50',
                'height' => '4.00',
                'hp' => 61,
                'attack' => 84,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/dragonair.png',
            ],
            [
                'name' => 'Dragonite',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Dragon',
                'weight' => '210.00',
                'height' => '2.20',
                'hp' => 91,
                'attack' => 134,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/dragonite.png',
            ],
            [
                'name' => 'Mewtwo',
                'species' => 'Genetic Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '122.00',
                'height' => '2.00',
                'hp' => 106,
                'attack' => 110,
                'defense' => 90,
                'is_legendary' => 1,
                'photo' => 'public/mewtwo.png',
            ],
            [
                'name' => 'Mew',
                'species' => 'New Species Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '4.00',
                'height' => '0.40',
                'hp' => 100,
                'attack' => 100,
                'defense' => 100,
                'is_legendary' => 1,
                'photo' => 'public/mew.png',
            ],
            [
                'name' => 'Chikorita',
                'species' => 'Leaf Pokemon',
                'primary_type' => 'Grass',
                'weight' => '6.40',
                'height' => '0.90',
                'hp' => 45,
                'attack' => 49,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/chikorita.png',
            ],
            [
                'name' => 'Bayleef',
                'species' => 'Leaf Pokemon',
                'primary_type' => 'Grass',
                'weight' => '15.80',
                'height' => '1.20',
                'hp' => 60,
                'attack' => 62,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/bayleef.png',
            ],
            [
                'name' => 'Meganium',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '100.00',
                'height' => '1.80',
                'hp' => 80,
                'attack' => 82,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/meganium.png',
            ],
            [
                'name' => 'Cyndaquil',
                'species' => 'Fire Mouse Pokemon',
                'primary_type' => 'Fire',
                'weight' => '7.90',
                'height' => '0.50',
                'hp' => 39,
                'attack' => 52,
                'defense' => 43,
                'is_legendary' => 0,
                'photo' => 'public/cyndaquil.png',
            ],
            [
                'name' => 'Quilava',
                'species' => 'Volcano Pokemon',
                'primary_type' => 'Fire',
                'weight' => '19.00',
                'height' => '0.90',
                'hp' => 58,
                'attack' => 64,
                'defense' => 58,
                'is_legendary' => 0,
                'photo' => 'public/quilava.png',
            ],
            [
                'name' => 'Typhlosion',
                'species' => 'Volcano Pokemon',
                'primary_type' => 'Fire',
                'weight' => '79.50',
                'height' => '1.60',
                'hp' => 78,
                'attack' => 84,
                'defense' => 78,
                'is_legendary' => 0,
                'photo' => 'public/typhlosion.png',
            ],
            [
                'name' => 'Totodile',
                'species' => 'Big Jaw Pokemon',
                'primary_type' => 'Water',
                'weight' => '9.50',
                'height' => '0.60',
                'hp' => 50,
                'attack' => 65,
                'defense' => 64,
                'is_legendary' => 0,
                'photo' => 'public/totodile.png',
            ],
            [
                'name' => 'Croconaw',
                'species' => 'Big Jaw Pokemon',
                'primary_type' => 'Water',
                'weight' => '25.00',
                'height' => '1.20',
                'hp' => 65,
                'attack' => 80,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/croconaw.png',
            ],
            [
                'name' => 'Feraligatr',
                'species' => 'Big Jaw Pokemon',
                'primary_type' => 'Water',
                'weight' => '88.80',
                'height' => '2.30',
                'hp' => 85,
                'attack' => 105,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/feraligatr.png',
            ],
            [
                'name' => 'Sentret',
                'species' => 'Scout Pokemon',
                'primary_type' => 'Normal',
                'weight' => '6.00',
                'height' => '0.80',
                'hp' => 35,
                'attack' => 46,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/sentret.png',
            ],
            [
                'name' => 'Furret',
                'species' => 'Ferret Pokemon',
                'primary_type' => 'Normal',
                'weight' => '32.50',
                'height' => '1.80',
                'hp' => 85,
                'attack' => 76,
                'defense' => 64,
                'is_legendary' => 0,
                'photo' => 'public/furret.png',
            ],
            [
                'name' => 'Hoothoot',
                'species' => 'Owl Pokemon',
                'primary_type' => 'Normal',
                'weight' => '21.00',
                'height' => '0.70',
                'hp' => 60,
                'attack' => 30,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/hoothoot.png',
            ],
            [
                'name' => 'Noctowl',
                'species' => 'Owl Pokemon',
                'primary_type' => 'Normal',
                'weight' => '40.80',
                'height' => '1.60',
                'hp' => 100,
                'attack' => 50,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/noctowl.png',
            ],
            [
                'name' => 'Ledyba',
                'species' => 'Five Star Pokemon',
                'primary_type' => 'Bug',
                'weight' => '10.80',
                'height' => '1.00',
                'hp' => 40,
                'attack' => 20,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/ledyba.png',
            ],
            [
                'name' => 'Ledian',
                'species' => 'Five Star Pokemon',
                'primary_type' => 'Bug',
                'weight' => '35.60',
                'height' => '1.40',
                'hp' => 55,
                'attack' => 35,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/ledian.png',
            ],
            [
                'name' => 'Spinarak',
                'species' => 'String Spit Pokemon',
                'primary_type' => 'Bug',
                'weight' => '8.50',
                'height' => '0.80',
                'hp' => 40,
                'attack' => 60,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/spinarak.png',
            ],
            [
                'name' => 'Ariados',
                'species' => 'Long Leg Pokemon',
                'primary_type' => 'Bug',
                'weight' => '33.00',
                'height' => '1.10',
                'hp' => 70,
                'attack' => 90,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/ariados.png',
            ],
            [
                'name' => 'Crobat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => '75.00',
                'height' => '1.80',
                'hp' => 85,
                'attack' => 90,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/crobat.png',
            ],
            [
                'name' => 'Chinchou',
                'species' => 'Light Pokemon',
                'primary_type' => 'Water',
                'weight' => '12.00',
                'height' => '0.60',
                'hp' => 75,
                'attack' => 38,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'public/chinchou.png',
            ],
            [
                'name' => 'Lanturn',
                'species' => 'Light Pokemon',
                'primary_type' => 'Water',
                'weight' => '22.50',
                'height' => '1.20',
                'hp' => 125,
                'attack' => 58,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/lanturn.png',
            ],
            [
                'name' => 'Pichu',
                'species' => 'Tiny Mouse Pokemon',
                'primary_type' => 'Electric',
                'weight' => '2.00',
                'height' => '0.30',
                'hp' => 20,
                'attack' => 40,
                'defense' => 15,
                'is_legendary' => 0,
                'photo' => 'public/pichu.png',
            ],
            [
                'name' => 'Cleffa',
                'species' => 'Star Shape Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '3.00',
                'height' => '0.30',
                'hp' => 50,
                'attack' => 25,
                'defense' => 28,
                'is_legendary' => 0,
                'photo' => 'public/cleffa.png',
            ],
            [
                'name' => 'Igglybuff',
                'species' => 'Balloon Pokemon',
                'primary_type' => 'Normal',
                'weight' => '1.00',
                'height' => '0.30',
                'hp' => 90,
                'attack' => 30,
                'defense' => 15,
                'is_legendary' => 0,
                'photo' => 'public/igglybuff.png',
            ],
            [
                'name' => 'Togepi',
                'species' => 'Togepi Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '1.50',
                'height' => '0.30',
                'hp' => 35,
                'attack' => 20,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'public/togepi.png',
            ],
            [
                'name' => 'Togetic',
                'species' => 'Happiness Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '3.20',
                'height' => '0.60',
                'hp' => 55,
                'attack' => 40,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'public/togetic.png',
            ],
            [
                'name' => 'Natu',
                'species' => 'Tiny Bird Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '2.00',
                'height' => '0.20',
                'hp' => 40,
                'attack' => 50,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/natu.png',
            ],
            [
                'name' => 'Xatu',
                'species' => 'Mystic Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '15.00',
                'height' => '1.50',
                'hp' => 65,
                'attack' => 75,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/xatu.png',
            ],
            [
                'name' => 'Mareep',
                'species' => 'Wool Pokemon',
                'primary_type' => 'Electric',
                'weight' => '7.80',
                'height' => '0.60',
                'hp' => 55,
                'attack' => 40,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/mareep.png',
            ],
            [
                'name' => 'Flaaffy',
                'species' => 'Wool Pokemon',
                'primary_type' => 'Electric',
                'weight' => '13.30',
                'height' => '1.20',
                'hp' => 70,
                'attack' => 55,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/flaaffy.png',
            ],
            [
                'name' => 'Ampharos',
                'species' => 'Light Pokemon',
                'primary_type' => 'Electric',
                'weight' => '30.00',
                'height' => '1.40',
                'hp' => 90,
                'attack' => 75,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/ampharos.png',
            ],
            [
                'name' => 'Bellossom',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '5.80',
                'height' => '0.40',
                'hp' => 75,
                'attack' => 80,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'public/bellossom.png',
            ],
            [
                'name' => 'Marill',
                'species' => 'Aqua Mouse Pokemon',
                'primary_type' => 'Water',
                'weight' => '8.50',
                'height' => '0.60',
                'hp' => 70,
                'attack' => 20,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/marill.png',
            ],
            [
                'name' => 'Azumarill',
                'species' => 'Aqua Rabbit Pokemon',
                'primary_type' => 'Water',
                'weight' => '28.50',
                'height' => '0.90',
                'hp' => 100,
                'attack' => 50,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'public/azumarill.png',
            ],
            [
                'name' => 'Sudowoodo',
                'species' => 'Imitation Pokemon',
                'primary_type' => 'Rock',
                'weight' => '38.00',
                'height' => '1.20',
                'hp' => 70,
                'attack' => 100,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'public/sudowoodo.png',
            ],
            [
                'name' => 'Politoed',
                'species' => 'Frog Pokemon',
                'primary_type' => 'Water',
                'weight' => '33.90',
                'height' => '1.10',
                'hp' => 90,
                'attack' => 65,
                'defense' => 75,
                'is_legendary' => 0,
                'photo' => 'public/politoed.png',
            ],
            [
                'name' => 'Hoppip',
                'species' => 'Cottonweed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '0.50',
                'height' => '0.40',
                'hp' => 35,
                'attack' => 35,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'public/hoppip.png',
            ],
            [
                'name' => 'Skiploom',
                'species' => 'Bloom Pokemon',
                'primary_type' => 'Grass',
                'weight' => '1.00',
                'height' => '0.60',
                'hp' => 55,
                'attack' => 45,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'public/skiploom.png',
            ],
            [
                'name' => 'Jumpluff',
                'species' => 'Jumpluff Pokemon',
                'primary_type' => 'Grass',
                'weight' => '0.80',
                'height' => '0.80',
                'hp' => 75,
                'attack' => 55,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'public/jumpluff.png',
            ],
            [
                'name' => 'Aipom',
                'species' => 'Long Tail Pokemon',
                'primary_type' => 'Normal',
                'weight' => '11.00',
                'height' => '0.80',
                'hp' => 55,
                'attack' => 70,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/aipom.png',
            ],
            [
                'name' => 'Sunkern',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '1.80',
                'height' => '0.80',
                'hp' => 30,
                'attack' => 30,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'public/sunkern.png',
            ],
            [
                'name' => 'Sunflora',
                'species' => 'Sun Pokemon',
                'primary_type' => 'Grass',
                'weight' => '8.50',
                'height' => '0.80',
                'hp' => 75,
                'attack' => 55,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'public/sunflora.png',
            ],
            [
                'name' => 'Yanma',
                'species' => 'Bug Pokemon',
                'primary_type' => 'Bug',
                'weight' => '38.00',
                'height' => '1.20',
                'hp' => 65,
                'attack' => 65,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/yanma.png',
            ],
            [
                'name' => 'Wooper',
                'species' => 'Water Fish Pokemon',
                'primary_type' => 'Water',
                'weight' => '8.50',
                'height' => '0.40',
                'hp' => 50,
                'attack' => 45,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'public/wooper.png',
            ],
            [
                'name' => 'Quagsire',
                'species' => 'Mud Fish Pokemon',
                'primary_type' => 'Water',
                'weight' => '75.00',
                'height' => '1.40',
                'hp' => 95,
                'attack' => 85,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'public/quagsire.png',
            ],
            [
                'name' => 'Espeon',
                'species' => 'Sun Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '26.50',
                'height' => '0.90',
                'hp' => 65,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 1,
                'photo' => 'public/espeon.png',
            ],
            [
                'name' => 'Umbreon',
                'species' => 'Moonlight Pokemon',
                'primary_type' => 'Dark',
                'weight' => '27.00',
                'height' => '1.00',
                'hp' => 95,
                'attack' => 65,
                'defense' => 110,
                'is_legendary' => 1,
                'photo' => 'public/umbreon.png',
            ],
            [
                'name' => 'Leafeon',
                'species' => 'Leaf Pokemon',
                'primary_type' => 'Grass',
                'weight' => '25.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 110,
                'defense' => 60,
                'is_legendary' => 1,
                'photo' => 'public/leafeon.png',
            ],
            [
                'name' => 'Glaceon',
                'species' => 'Fresh Snow Pokemon',
                'primary_type' => 'Ice',
                'weight' => '25.00',
                'height' => '0.80',
                'hp' => 65,
                'attack' => 60,
                'defense' => 110,
                'is_legendary' => 1,
                'photo' => 'public/glaceon.png',
            ],
            [
                'name' => 'Sylveon',
                'species' => 'Intertwining Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '23.50',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 1,
                'photo' => 'public/sylveon.png',
            ],
            [
                'name' => 'Articuno',
                'species' => 'Freeze Pokemon',
                'primary_type' => 'Ice',
                'weight' => '55.40',
                'height' => '1.70',
                'hp' => 90,
                'attack' => 85,
                'defense' => 100,
                'is_legendary' => 1,
                'photo' => 'public/articuno.png',
            ],
            [
                'name' => 'Zapdos',
                'species' => 'Electric Pokemon',
                'primary_type' => 'Electric',
                'weight' => '52.60',
                'height' => '1.60',
                'hp' => 90,
                'attack' => 90,
                'defense' => 85,
                'is_legendary' => 1,
                'photo' => 'public/zapdos.png',
            ],
            [
                'name' => 'Moltres',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '60.00',
                'height' => '2.00',
                'hp' => 90,
                'attack' => 100,
                'defense' => 90,
                'is_legendary' => 1,
                'photo' => 'public/moltres.png',
            ],
            [
                'name' => 'Celebi',
                'species' => 'Time Travel Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '5.00',
                'height' => '0.60',
                'hp' => 100,
                'attack' => 100,
                'defense' => 100,
                'is_legendary' => 1,
                'photo' => 'public/celebi.png',
            ]

        ]);
    }
}
